// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.pairec.recallengine.recallenginefb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BoolValueColumn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static BoolValueColumn getRootAsBoolValueColumn(ByteBuffer _bb) { return getRootAsBoolValueColumn(_bb, new BoolValueColumn()); }
  public static BoolValueColumn getRootAsBoolValueColumn(ByteBuffer _bb, BoolValueColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public BoolValueColumn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean value(int j) { int o = __offset(4); return o != 0 ? 0!=bb.get(__vector(o) + j * 1) : false; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public BooleanVector valueVector() { return valueVector(new BooleanVector()); }
  public BooleanVector valueVector(BooleanVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createBoolValueColumn(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startTable(1);
    BoolValueColumn.addValue(builder, valueOffset);
    return BoolValueColumn.endBoolValueColumn(builder);
  }

  public static void startBoolValueColumn(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, boolean[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addBoolean(data[i]); return builder.endVector(); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endBoolValueColumn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public BoolValueColumn get(int j) { return get(new BoolValueColumn(), j); }
    public BoolValueColumn get(BoolValueColumn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

