// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.pairec.recallengine.recallenginefb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldValueColumnTable extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static FieldValueColumnTable getRootAsFieldValueColumnTable(ByteBuffer _bb) { return getRootAsFieldValueColumnTable(_bb, new FieldValueColumnTable()); }
  public static FieldValueColumnTable getRootAsFieldValueColumnTable(ByteBuffer _bb, FieldValueColumnTable obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldValueColumnTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte fieldValueColumnType() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Table fieldValueColumn(Table obj) { int o = __offset(6); return o != 0 ? __union(obj, o + bb_pos) : null; }

  public static int createFieldValueColumnTable(FlatBufferBuilder builder,
      byte fieldValueColumnType,
      int fieldValueColumnOffset) {
    builder.startTable(2);
    FieldValueColumnTable.addFieldValueColumn(builder, fieldValueColumnOffset);
    FieldValueColumnTable.addFieldValueColumnType(builder, fieldValueColumnType);
    return FieldValueColumnTable.endFieldValueColumnTable(builder);
  }

  public static void startFieldValueColumnTable(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addFieldValueColumnType(FlatBufferBuilder builder, byte fieldValueColumnType) { builder.addByte(0, fieldValueColumnType, 0); }
  public static void addFieldValueColumn(FlatBufferBuilder builder, int fieldValueColumnOffset) { builder.addOffset(1, fieldValueColumnOffset, 0); }
  public static int endFieldValueColumnTable(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldValueColumnTable get(int j) { return get(new FieldValueColumnTable(), j); }
    public FieldValueColumnTable get(FieldValueColumnTable obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

