// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.pairec.recallengine.recallenginefb;

@SuppressWarnings("unused")
public final class FieldValueColumn {
  private FieldValueColumn() { }
  public static final byte NONE = 0;
  public static final byte UInt8ValueColumn = 1;
  public static final byte Int32ValueColumn = 2;
  public static final byte Int64ValueColumn = 3;
  public static final byte FloatValueColumn = 4;
  public static final byte DoubleValueColumn = 5;
  public static final byte StringValueColumn = 6;
  public static final byte BoolValueColumn = 7;
  public static final byte MultiInt32ValueColumn = 8;
  public static final byte MultiInt64ValueColumn = 9;
  public static final byte MultiFloatValueColumn = 10;
  public static final byte MultiDoubleValueColumn = 11;
  public static final byte MultiStringValueColumn = 12;
  public static final byte UnknownValueColumn = 13;

  public static final String[] names = { "NONE", "UInt8ValueColumn", "Int32ValueColumn", "Int64ValueColumn", "FloatValueColumn", "DoubleValueColumn", "StringValueColumn", "BoolValueColumn", "MultiInt32ValueColumn", "MultiInt64ValueColumn", "MultiFloatValueColumn", "MultiDoubleValueColumn", "MultiStringValueColumn", "UnknownValueColumn", };

  public static String name(int e) { return names[e]; }
}

