// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.pairec.recallengine.recallenginefb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Int8ValueColumn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static Int8ValueColumn getRootAsInt8ValueColumn(ByteBuffer _bb) { return getRootAsInt8ValueColumn(_bb, new Int8ValueColumn()); }
  public static Int8ValueColumn getRootAsInt8ValueColumn(ByteBuffer _bb, Int8ValueColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Int8ValueColumn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte value(int j) { int o = __offset(4); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ByteVector valueVector() { return valueVector(new ByteVector()); }
  public ByteVector valueVector(ByteVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createInt8ValueColumn(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startTable(1);
    Int8ValueColumn.addValue(builder, valueOffset);
    return Int8ValueColumn.endInt8ValueColumn(builder);
  }

  public static void startInt8ValueColumn(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, byte[] data) { return builder.createByteVector(data); }
  public static int createValueVector(FlatBufferBuilder builder, ByteBuffer data) { return builder.createByteVector(data); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endInt8ValueColumn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Int8ValueColumn get(int j) { return get(new Int8ValueColumn(), j); }
    public Int8ValueColumn get(Int8ValueColumn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

