// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.pairec.recallengine.recallenginefb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MatchRecords extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MatchRecords getRootAsMatchRecords(ByteBuffer _bb) { return getRootAsMatchRecords(_bb, new MatchRecords()); }
  public static MatchRecords getRootAsMatchRecords(ByteBuffer _bb, MatchRecords obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MatchRecords __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String fieldName(int j) { int o = __offset(4); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int fieldNameLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public StringVector fieldNameVector() { return fieldNameVector(new StringVector()); }
  public StringVector fieldNameVector(StringVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable recordColumns(int j) { return recordColumns(new com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable(), j); }
  public com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable recordColumns(com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int recordColumnsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable.Vector recordColumnsVector() { return recordColumnsVector(new com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable.Vector()); }
  public com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable.Vector recordColumnsVector(com.aliyun.openservices.pairec.recallengine.recallenginefb.FieldValueColumnTable.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public long docCount() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String tracers(int j) { int o = __offset(10); return o != 0 ? __string(__vector(o) + j * 4) : null; }
  public int tracersLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public StringVector tracersVector() { return tracersVector(new StringVector()); }
  public StringVector tracersVector(StringVector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public String tableName() { int o = __offset(12); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer tableNameAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }
  public ByteBuffer tableNameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 12, 1); }

  public static int createMatchRecords(FlatBufferBuilder builder,
      int fieldNameOffset,
      int recordColumnsOffset,
      long docCount,
      int tracersOffset,
      int tableNameOffset) {
    builder.startTable(5);
    MatchRecords.addDocCount(builder, docCount);
    MatchRecords.addTableName(builder, tableNameOffset);
    MatchRecords.addTracers(builder, tracersOffset);
    MatchRecords.addRecordColumns(builder, recordColumnsOffset);
    MatchRecords.addFieldName(builder, fieldNameOffset);
    return MatchRecords.endMatchRecords(builder);
  }

  public static void startMatchRecords(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addFieldName(FlatBufferBuilder builder, int fieldNameOffset) { builder.addOffset(0, fieldNameOffset, 0); }
  public static int createFieldNameVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startFieldNameVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRecordColumns(FlatBufferBuilder builder, int recordColumnsOffset) { builder.addOffset(1, recordColumnsOffset, 0); }
  public static int createRecordColumnsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRecordColumnsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addDocCount(FlatBufferBuilder builder, long docCount) { builder.addLong(2, docCount, 0L); }
  public static void addTracers(FlatBufferBuilder builder, int tracersOffset) { builder.addOffset(3, tracersOffset, 0); }
  public static int createTracersVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTracersVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addTableName(FlatBufferBuilder builder, int tableNameOffset) { builder.addOffset(4, tableNameOffset, 0); }
  public static int endMatchRecords(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishMatchRecordsBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedMatchRecordsBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MatchRecords get(int j) { return get(new MatchRecords(), j); }
    public MatchRecords get(MatchRecords obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

