// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.pairec.recallengine.recallenginefb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MultiDoubleValue extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MultiDoubleValue getRootAsMultiDoubleValue(ByteBuffer _bb) { return getRootAsMultiDoubleValue(_bb, new MultiDoubleValue()); }
  public static MultiDoubleValue getRootAsMultiDoubleValue(ByteBuffer _bb, MultiDoubleValue obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MultiDoubleValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double value(int j) { int o = __offset(4); return o != 0 ? bb.getDouble(__vector(o) + j * 8) : 0; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public DoubleVector valueVector() { return valueVector(new DoubleVector()); }
  public DoubleVector valueVector(DoubleVector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), bb) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(4, 8); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 8); }

  public static int createMultiDoubleValue(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startTable(1);
    MultiDoubleValue.addValue(builder, valueOffset);
    return MultiDoubleValue.endMultiDoubleValue(builder);
  }

  public static void startMultiDoubleValue(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, double[] data) { builder.startVector(8, data.length, 8); for (int i = data.length - 1; i >= 0; i--) builder.addDouble(data[i]); return builder.endVector(); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(8, numElems, 8); }
  public static int endMultiDoubleValue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MultiDoubleValue get(int j) { return get(new MultiDoubleValue(), j); }
    public MultiDoubleValue get(MultiDoubleValue obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

