// automatically generated by the FlatBuffers compiler, do not modify

package com.aliyun.openservices.pairec.recallengine.recallenginefb;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class MultiFloatValueColumn extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_2_10(); }
  public static MultiFloatValueColumn getRootAsMultiFloatValueColumn(ByteBuffer _bb) { return getRootAsMultiFloatValueColumn(_bb, new MultiFloatValueColumn()); }
  public static MultiFloatValueColumn getRootAsMultiFloatValueColumn(ByteBuffer _bb, MultiFloatValueColumn obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public MultiFloatValueColumn __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue value(int j) { return value(new com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue(), j); }
  public com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue value(com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int valueLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue.Vector valueVector() { return valueVector(new com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue.Vector()); }
  public com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue.Vector valueVector(com.aliyun.openservices.pairec.recallengine.recallenginefb.MultiFloatValue.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createMultiFloatValueColumn(FlatBufferBuilder builder,
      int valueOffset) {
    builder.startTable(1);
    MultiFloatValueColumn.addValue(builder, valueOffset);
    return MultiFloatValueColumn.endMultiFloatValueColumn(builder);
  }

  public static void startMultiFloatValueColumn(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(0, valueOffset, 0); }
  public static int createValueVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startValueVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endMultiFloatValueColumn(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public MultiFloatValueColumn get(int j) { return get(new MultiFloatValueColumn(), j); }
    public MultiFloatValueColumn get(MultiFloatValueColumn obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

